### ISSUE TITLE
Format everything

### ISSUE THREAD

**Issue by Shillaker** [faasm/faasm#303]
`clang-format` for C/C++, `black` for Python

- [x] Apply clang-format everywhere
- [x] Add clang-format check to build
- [x] Apply Black everywhere
- [x] Add Black check to build
- [x] Apply clang-format to other non-fork repos in `faasm` org
- [x] Add CI check for formatting in non-fork repos in `faasm` org

**Comment by csegarragonz** [comment]
I suggest that, as a part of this refactor, we include a small section either on [Development](https://github.com/lsds/faasm/blob/master/docs/development.md), or as a new _Contribuiting_ section, on the code format we follow and maybe some examples on how to enforce it (i.e. integrate it with different text editors).

PS: unsure if it's worth it if we include a style phase in the CI pipeline.

**Comment by Shillaker** [comment]
I think the CI check and a little note in [development.md](docs/development.md) to say that we use clang-format and black should do the trick. They're both sufficiently well known tools that people can work out how to integrate them into their own environments.

This can be done as part of the PR to reformat the repo.

**Comment by csegarragonz** [comment]
Just checking-in here to remind ourselves to use the updated `run_clang_format.sh` with the newline trailing (I don't know in which circumstances we could forget about it, but anyway).
