### ISSUE TITLE
Broken Ansible Playbook for Catch2

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faasm#325]
I am having troubles linking with the `catch2` library. The ansible playbook is broken as there's a [broken link](https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp), noted in their repo catchorg/catch2#2050.

I am aware that we are moving to a `CMake` based [integration](https://github.com/faasm/faasm/blob/66e45a9bbfd232cf46d96be2ddb634b2b0a7bdc1/cmake/ExternalProjects.cmake#L43) (I was about to do that myself) in #322.

I only have then one question remaining (and hence the issue). If the dependency is downloaded through `CMake` isn't the [ansible role](https://github.com/faasm/faasm/blob/toolchain-split/ansible/catch.yml) obsolete? You seem to have deleted some but not this one.

PS: I am also adding this issue as a `known-problem` whilst the #322 isn't merged.

**Comment by Shillaker** [comment]
Yep, this will be closed by #322
