### ISSUE TITLE
[DISCUSSION] How should the related development environments look like?

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faasm#334]
After #322, we now have a smooth containerized development enviornment for `faasm`. Which I must admit I very much like.

However, the `faasm-experiments` repo (among others) has ben, rightfully, left out of the picture. I agree it should be out, but then we should provide a way to develop. I am bringing this issue up for `faasm-experiments`, but this works similarly for `faasm-toolchain` or even `faabric`.

The issue here is not to clutter too much the current `compose` files, yet provide a unified development environment. We could use this issue to brainstorm some suggestions, here are the first that come to mind.

**1. Use git from within the container:**
+ This approach would have us pushing/pulling from _within_ the container. It has, however, quite some drawbacks (I really don't like it myself).
+ First of all, we'd have to ship the container image with our git credentials (non-desirable) and risk to lose untracked changes if the service stops.
+ On those same lines, persistance, is not _that_ bad. With the change from `docker-compose run` to `docker-compose up` introduced in #332 (to be merged at the time of the writing), services persist even if no terminal is attached to them. So changes would only be lost (unless manually stopped) when shutting down the computer (i.e. never if you are working remotely).
+ However, it is, on a broader sense, contary to my idea of the containerized working environment.

**2. Mount the additional repositories as shared volumes:**
+ The same way we are currently persisting changes in the `faasm` repo, we could mount whichever additional repositories we wanted to use. A few notes on this proposal.
+ Observe that this would imply us enforcing a particular directory structure _outside_ `faasm` for developers. For instance, having all `faasm-*` dirs on the same level.
+ Additionally, this should _definately_ be left outside the main `docker-compose-cli.yml` but yet (in my opinion) tracked in the main repository.
+ My proposal is to use `docker-compose` [override capabilities](https://docs.docker.com/compose/extends/#multiple-compose-files).
+ We could also provide a switch to enable/disable repos (i.e. mount experiments or not, mount toolchain or not, ...).
+ Unfortunately, this would mean that we'd have to maintain a `docker-compose-cli.overrides.yml` and include it in the invokations in `bin/cli.sh` (which might already be a bit cluttered).

I don't have a clear answer for this, so I am open to suggestions and discussion!

**Comment by Shillaker** [comment]
I get your points, although are you assuming we'd still run this development environment from Faasm? I would think of them all as separate projects, that inherit from one another. For example, in the experiments repo we would have a CLI container that inherits from the Faasm one, and set up a separate docker-compose environment. 

Faabric should be seen as a library/ middleware, and not a system, therefore it's a slightly different proposition. We could still create a development container though, this would just inherit from the existing Faabric container that already exists in that repo.
