### ISSUE TITLE
No support for function override on upload

### ISSUE THREAD

**Issue by xushangning** [faasm/faasm#381]
- Version: master (3ea590b3dd5786337955a5ba2b7dbaa7e2ae0da1)
- Description: Even if a new wasm file for a function e.g. demo/hello is uploaded, the old version of the function is executed.

This can be easily reproduced by first compiling, uploading, and invoking the demo/hello function that comes with the repo, and then just modify the hello function a little e.g. change the string to output and recompile and upload the new function. In this case, the old string is still printed when we try to invoke demo/hello.

This issue is especially inconvenient for debugging functions. Right now I have to delete all the containers every time I want to upload a new function if it has the same name as a previously-uploaded function.

**Comment by Shillaker** [comment]
Hi @xushangning , thanks for the message. You are correct, this is an annoying issue that we've thought about changing for a while but never got round to it. However, you shouldn't have to delete all the containers, you just need to restart some of them. If you're using the docker-compose set-up, the steps would be:

- Upload the modified function
- Restart `worker`, `upload`, `redis-queue` (i.e. `docker-compose restart worker upload redis-queue`)
- Invoke the function

We're currently on Xmas holidays but will likely fix this in the new year.

**Comment by xushangning** [comment]
Got it. I'll try to narrow down the containers to restart.

Feel free to keep this issue open to track the bug or close it if it clutters the the issue tracker.

**Comment by xushangning** [comment]
I just did a fresh checkout of master (2a7421df552b0d14b3d03f2c4353123f35413e52) and restarting containers (be it all containers or 3 containers you've mentioned) doesn't work. After restart, the old version of function is still invoked.

**Comment by Shillaker** [comment]
Hi @xushangning I'll have a look at this now.

**Comment by Shillaker** [comment]
Hey @xushangning sorry this took so long, turned out there was a bit more complexity involved in updating functions than I'd imagined. This is mainly due to the various layers of caching performed in distributed workers. 

Although it's not a great solution, I've fixed up the `flush` operation, which clears out all cached function data from all the nodes. This means the workflow might look something like:

```bash
# Normal compile and upload
inv compile demo hello
inv upload demo hello

# Invoke and see "Hello Faasm!"
inv invoke demo hello

# Edit the function to print something else (file at func/demo/hello.cpp)

# Compile and upload again
inv compile demo hello
inv upload demo hello

# Clear out all caches
inv flush

# Invoke the function and see the new message
inv invoke demo hello
```

That should work with the latest master and latest tag (`0.5.8`).

If you're interested in actually messing with the code for Faasm itself, I've updated the [development docs](https://github.com/faasm/faasm/blob/master/docs/development.md) to describe running a local development cluster.

**Comment by xushangning** [comment]
Sorry for the delay in response... I tested master (ac8955d02ca6f1a5eceeb71d51d709876cdd1c78) just now with the hello function and it was still the old version of the function that got executed.

Is there any debug information I can provide (files deleted or data structures updated during flushing)?

Also, during this time I've found a reliable workaround to this problem: Recreate the upload and worker containers prior to uploading the new function.

**Comment by Shillaker** [comment]
Hi @xushangning, @csegarragonz has kindly pointed out that the instructions I gave were actually in the wrong order, and that you have to run `flush` _before_ running `upload`. 

I've updated my previous comment now, let me know if that works.

**Comment by xushangning** [comment]
> you have to run `flush` _before_ running `upload`.

Wow! You're right. Now it works wonderfully.

**Comment by xushangning** [comment]
Summary: The sequence of operations that works on my computer is actually upload → invoke → flush → invoke. The key point is that `flush` must be followed by `invoke` to be effective.

I still came across this issue when playing around Faasm and did some experiments on ac8955d02ca6f1a5eceeb71d51d709876cdd1c78 using the `cpp_example` function. In the following comment, 

> > you have to run `flush` _before_ running `upload`.
> 
> Wow! You're right. Now it works wonderfully.

the tip worked for me not because I run `flush` before `upload`, but simply because I run `invoke` again. My complete sequence of operations should be compile → upload → flush → **invoke (old)** → (reading @Shillaker's comment) → flush → upload → invoke.

I consider this problem fixed so I won't reopen the issue.

**Comment by Shillaker** [comment]
Ok great, thanks so much for the detailed summary @xushangning !

Hopefully we'll get round to fixing this properly soon, but unfortunately it's currently not high on the priority list. Glad the `flush` will work in the meantime though.
