### ISSUE TITLE
Splitting SGX Attestation PR

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faasm#447]
This is my suggestion on how to split #357 which currently is too large to work with.

**PR 1: SGX cluster w/ key manager**
* Define a `docker-compose` file, something like: `docker/docker-compose-sgx.yml` to run SGX-Faasm deployments.
* Add a service for the key manager (as you do in `docker-compose-sgx-attesation.yml`. Is `mongo` needed?
* The file should set the necessary environment variables.
* Currently, the key manager lives in a [separate repo](https://github.com/faasm/keymanager/).
* We should move the dockerfile there as well (`docker/keymanager.dockerfile`), and add scripts to generate the images, and upload them to docker hub. See [this](https://github.com/faasm/experiment-base/blob/master/tasks/container.py) for an example among others.
* Note that this may involve 1 PR in faasm and one in the key manager.

**PR 2: Crypto API** (#449, #452)
* In the PR, the `invoke_impl` method contains all the logic for encrypting and decrypting.
* At the same time, the (same?) crypto methods are re-defined in CPP files.
* My suggestion is to add a subdir `src/sgx/crypto` that defines an external API with `encryptMsg` and `decryptMsg`, that interacts with both python and CPP code.
* Ideally this would also handle all interactions with the key manager.
* Add tests for the crypto external API (`encrypt`, `decrypt`).
* The idea is that the crypto module is not bound to attestation.
* Hide the particular algorithms we are using to encrypt/decrypt and use generic constants like (`ENC_KEY_SIZE`). The particular algorithms could be part of `faasm`'s configuration.

**PR 3: Wasm parser**
* There's a massive [`wasm.py`](https://github.com/faasm/faasm/pull/357/files#diff-23e3e6c1d454d810a90daf357a24abe52522909aa26e3cdc56260607e3c7692b) file here.
* AFAICT it parses a WebAssembly file. My first question is: how does this differ from well-maintained solutions like [`wasm-tools/wasmparser`](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasmparser) or [`wasmskd/wasmparser`](https://github.com/wasdk/wasmparser)?
* Do we need to roll our own in-house solution?
* Whichever option we stick with, I suggest adding it as an `ExternalProject` and have it live in another repo.

**PR 4: Integrate SGX with crypto module**
* This PR aims to integrate the functioning of SGX with PR3.
* In particular, it should encrypt/decrypt inputs and outputs.
* If the interaction with the key manager is not too complex, could be implemented here.
* Add a configuration variable that allows the SGX to run in test mode (aka without encryption) so that current tests pass.
* Add corresponding tests to run with encrypted inputs.

**PR 5: Attestation**
* Attestation should be independent of the way functions run inside enclaves in `faasm` and of the way we do crypto.
* Attestation code could live in `src/sgx/attestation`.
* Attestation must use [DCAP](https://github.com/intel/SGXDataCenterAttestationPrimitives) (it is currently a big unknown how hard it will be to integrate DCAP).
* This PR should _only_ add logic for an enclave to renew its attestation credentials with the key manager upon request.
* Ideally we could test this method as part of the testing suite in `tests/tests/sgx/test_attestation.cpp`, maybe we need to fake the key manager, but it should be alright.

**PR 6: Chaining and attested stacks**

**PR 7: Policies**
* It is still not even clear how we will use policies in the project, so we should leave this for a future PR.

**Comment by csegarragonz** [comment]
@Shillaker and @dgoltzsche this is the first tentative plan on how to merge the #357. Feel free to add comments with suggestions or edit the text itself (don't know if you can).

The underlying idea is that attestation is orthogonal to crypto, policies, parsing, and the integration of the previous upstream. Each PR should expose a reasonable API that can both (1) be tested, and (2) be called from other internal APIs. Further, we want to hide implementation details like the algorithm we use to encrypt very deep within the codebase, and have these details be configurable through `faasm`'s native config (through environment variables).

David, in my opinion good starting points are 3,4, and 5. As they have no overlap with other system-related PRs I have in my stack now.

**Comment by dgoltzsche** [comment]
Nice, thanks for putting in the work! Some feedback:

- **PR 1:** Yes, `mongo` is necessary. The [keymanager](https://github.com/faasm/keymanager) expects a mongodb to use it for storing keys
- **PR 2:** What's the last point?
- **PR 4:** Rewriting parts of `wasm.py` using existing parsers should be possible, but might not be worth the effort.

**Comment by Shillaker** [comment]
Great, looks good. Some comments:

PR 1: does the docker-compose stuff mentioned here need to live in this repo? Is it needed for testing? I think it could actually live in the keymanager repo which would then have the faasm repo as a submodule.

PRs 1 and 2: I would merge these two as it'll be adding then removing the same files. I'd forgotten the keymanager needs mongodb, let's take that discussion offline. 

PR 3: I'm surprised by how much code we need just to encrypt and decrypt files, is there not some off-the-shelf C++ library that can do this? I agree with the approach to putting it into a single C++ executable that we call from Python to avoid the duplication.

PR 4: I agree with both of you, it's pretty large and should be farmed off into a separate repo, but equally we don't want to waste time reworking it once we have cleaved it off. 

PR 5: Why do we need the unencrypted version? If the "real" thing uses encryption can't we just test with encryption on?

**Comment by csegarragonz** [comment]
Re-numbered the PRs according to Simon's comment. Will add links to the actual PR's as they come in.

**Comment by csegarragonz** [comment]
Really out-of-date after today's offline discussion, so will close.
