### ISSUE TITLE
Add e2e tests in place of quick-start

### ISSUE THREAD

**Issue by Shillaker** [faasm/faasm#533]
Quick-start tests were added to make sure the "quick start" instructions continue to work, but have proven themselves to be an effective end-to-end integration test.

The quick-start instructions actually just use the latest container versions (i.e. not the latest code). The quick-start tests therefore do their job, but this means the next time someone builds a new container, they have to sort out all the errors from changes made since the last container build.

Solution:
- Run the existing quick-start tests after the release build.
- Add a new "e2e-tests" in the current PR workflow, which does something similar, but with the most recent build of the code.

**Comment by csegarragonz** [comment]
Should be closed by a combination of #722 and #726.

The former, add the option to run the quick start tests mounting the current code version.

The latter do a `quick-start`-like test on a production k8s cluster (on-demand).

I'm gonna wait for the PRs to be merged to close this issue.
