### ISSUE TITLE
Can't find any collection named 'tasks'!

### ISSUE THREAD

**Issue by zavalyshyn** [faasm/faasm#566]
Hi,
I'm trying your project's code (more specifically python samples) but anytime I try to execute an "inv" command I get an error saying the following:
```
$ docker-compose run python /bin/bash

----------------------------------
CPP CLI
Version: 0.1.0
Project root: /code/cpp/bin/..
Mode: terminal
----------------------------------

(cpp) root@8d4b6b977a1a:/code/python# inv func
Can't find any collection named 'tasks'!
(cpp) root@8d4b6b977a1a:/code/python#
```
I receive the same error when I try cpp samples as well. Am I missing something?

**Comment by Shillaker** [comment]
Seems to work for me, can I just double check you're running off the latest master, and can you let me know your OS and shell?

**Comment by zavalyshyn** [comment]
Simon, thanks for such a speedy response. 
I've just tested your suggested command (git submodule update) and it worked brilliantly. I can compile and invoke a cpp hello function successfully. Will continue exploring FAASM.
Thanks for your hard work on this and congrats on ATC paper!
