### ISSUE TITLE
Errors in WAMR filesystem support

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faasm#635]
Two tests are currently failing, both related to the WAMR filesystem implementation:

- `Test fread`: https://github.com/faasm/faasm/blob/main/tests/test/faaslet/test_filesystem.cpp
- `Test accessing shared files`: https://github.com/faasm/faasm/blob/main/tests/test/faaslet/test_shared_files.cpp 

These are perhaps related, perhaps not related, but both failures seem to be sporadic.

**Comment by Shillaker** [comment]
We don't really have time to fix this at the moment so let's just disable the test(s) with a note then leave this issue open.

**Comment by Shillaker** [comment]
I just took another look and this isn't actually failing on the sanitiser build, it's failing on the normal build.
