### ISSUE TITLE
Issue with `FAASM_BUILD_DIR`

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faasm#636]
When running outside a container but with the virtual environment enabled (i.e. `source ./bin/workon.sh`-ed), the envrionment variable `FAASM_BUILD_DIR` exported in `./bin/workon.sh` overwrites the one in `.env`, effectively disabling the shared mount from e.g. the CLI with other containers in the development cluster.

**Comment by Shillaker** [comment]
I'm not sure I understand what you mean by "running" here, what do you mean specifically?

`workon.sh` will set `FAASM_BUILD_DIR` to `${PROJ_ROOT}/dev/native/build` when run outside a container, and to `/build/faasm` when run inside a container. Therefore, if you run `docker-compose` commands from the terminal having run `workon.sh`, it will see the `native/build` version. That means, for example, running `./bin/cli.sh` from a `workon`-ed shell will see the non-containerised build dir. The solution to this would be to set `FAASM_BUILD_DIR` explicitly in the `cli.sh` script.
