### ISSUE TITLE
Compose v3 support

### ISSUE THREAD

**Issue by mmathys** [faasm/faasm#647]
The `bin/cli.sh` script could be updated to support compose v3. The command `docker-compose` was deprecated and `docker compose` is used instead.

Another option is to add a note in the docs.

**Comment by Shillaker** [comment]
We use `docker-compose` in a few places throughout the project, not just in `cli.sh`, but as long as we do a find-and-replace to `docker compose`, I think that's fine. It's relatively straightforward to upgrade.
