### ISSUE TITLE
Question about different runtimes

### ISSUE THREAD

**Issue by wilsonwang371** [faasm/faasm#649]
Hi,

I am wondering why Faasm has two wasm runtimes support(WAMR & WAVM).

What is the reason to have two of them instead of just having one?

Thanks

**Comment by Shillaker** [comment]
Hi @wilsonwang371,

WAVM is our best-supported runtime, and has historically been more performant, and provide more comprehensive support for the latest wasm features. 

We currently only include WAMR to support SGX.

Why do you ask?

**Comment by wilsonwang371** [comment]
I am recently doing research on different serverless frameworks. While I am reading Faasm source code I found this.

Btw, have you ever compared Faasm with similar alternatives? For example: Ray framework.

**Comment by Shillaker** [comment]
We've not compared with Ray directly, but have benchmarked against other serverless platforms. The only published results on the topic can be found in our ATC paper mentioned in the README. 

I'm going to close this issue for now as it's not related to an issue with the code, but feel free to email me if you'd like to discuss any specific research topics.
