### ISSUE TITLE
Faasm development: inv dev.cmake clang-13 and clang++-13 missing

### ISSUE THREAD

**Issue by FlowDrucka64** [faasm/faasm#653]
When exectuing `inv dev.cmake` in the containerized faasm cli (run with `./bin/cli.sh faasm`) the following happens:

----------------------------------
Faasm CLI
Version: 0.8.12
Project root: /usr/local/code/faasm
Mode: container
----------------------------------

(faasm) root@3d494048d8b8:/usr/local/code/faasm# inv dev.cmake
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++-13 -DCMAKE_C_COMPILER=/usr/bin/clang-13 -DCMAKE_INSTALL_PREFIX=/usr/local    -DFAASM_USE_SANITISER=None -DFAABRIC_USE_SANITISER=None -DFAASM_SGX_MODE=Disabled  /usr/local/code/faasm
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    /usr/bin/clang-13

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/clang++-13

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/build/faasm/CMakeFiles/CMakeOutput.log".
See also "/build/faasm/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.8/dist-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.8/dist-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.8/dist-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/code/faasm/faasmcli/faasmcli/tasks/dev.py", line 69, in cmake
    run(cmd_str, shell=True, check=True, cwd=FAASM_BUILD_DIR)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++-13 -DCMAKE_C_COMPILER=/usr/bin/clang-13 -DCMAKE_INSTALL_PREFIX=/usr/local    -DFAASM_USE_SANITISER=None -DFAABRIC_USE_SANITISER=None -DFAASM_SGX_MODE=Disabled  /usr/local/code/faasm' returned non-zero exit status 1.

It seems like the clang-13 and clang++-13 compilers are not available within the container.
As far as I can tell from the `cli.dockerfile` they should get installed through 
`# Install various deps
RUN apt-get update
RUN apt-get install -y \
    clang-tidy-10 \
    clang-tidy-13 \
    doxygen \
    libpython3-dev \
    python3-dev \
    python3-pip \
    python3-venv \
    libcairo2-dev \
    python3-cairo \
    vim`
whithin the container but arent?

Am I missing something here?

**Comment by Shillaker** [comment]
Yes you're right, `clang-13` is installed in the Docker image. This works for me:

```bash
# Execute "which clang-13" in latest CLI container
docker run faasm/cli:0.8.12 which clang-13

# Output
/usr/bin/clang-13
```

This also works:

```bash
# Run a terminal in the container
docker run -it faasm/cli:0.8.12 /bin/bash

# Run cmake
inv dev.cmake
```

Can you also try these and confirm that you're running `faasm/cli:0.8.12`?

**Comment by FlowDrucka64** [comment]
It works when running it like you showed.
After closer inspection I noticed that I had two CLI images (an older one and 0.8.12) pulled for some reason and was presumably defaulting to the older one which is somewhat confusing since it even said 
```
Faasm CLI
Version: 0.8.12
Project root: /usr/local/code/faasm
Mode: container
```
when firing up the container but whatever it seems to work now.
Thank you!

**Comment by csegarragonz** [comment]
When running the development container (`./bin/cli.sh faasm`) we mount your checked out code to the project root, and read the version from there.

If you have stale containers lingering around, it could be that the code version and your container are out of date. In this cases removing all containers `docker-compose down` should do the trick.

I will close the issue, feel free to re-open it or open a new one if you run into other problems.
