### ISSUE TITLE
Make scripts zsh proof

### ISSUE THREAD

**Issue by mmathys** [faasm/faasm#666]
E.g. [`workon.sh`](https://github.com/faasm/faasm/blob/bfb77185809a03a75113d99fe36b8c58112b7fa8/bin/workon.sh#L12..L15) is zsh proof, but not [`create_venv.sh`](https://github.com/faasm/faasm/blob/main/bin/create_venv.sh#L5). `bash` and `zsh` evaluate the expression for `THIS_DIR` differently.

**Comment by eigenraven** [comment]
See <https://github.com/auto-ndp/faabric/blob/master/bin/workon.sh#L10>, maybe I should PR this upstream :sweat_smile:

**Comment by mmathys** [comment]
That solution looks clean! Yeah this may be a good idea :)
