### ISSUE TITLE
Fix workon.sh prefix

### ISSUE THREAD

**Issue by mmathys** [faasm/faasm#667]
In [`workon.sh`](https://github.com/faasm/faasm/blob/bfb77185809a03a75113d99fe36b8c58112b7fa8/bin/workon.sh#L88), the `PS1` is updated the new virtual environment. If `workon.sh` is executed multiple times (e.g. when switching between environments), the old environment is kept in this variable, creating large string of virtual envs like this:

```bash
(faasm-exp) (faasm-exp) (faasm) (faasm-exp) (faasm) mmathys@koala9:~/experiment-base$
```

An easy fix could be to change this line to

```
export PS1="(faasm)"
```

**Comment by mmathys** [comment]
I figured out a simple workaround.

```bash
export PS1=`sed -e "s/(.*) //" <<< $PS1`
export PS1="(faasm) $PS1"
```

The first command filters out the prefix (if it exists), then adds the prefix. What do you think?

**Comment by eigenraven** [comment]
This would also filter out any parenthesized components of your default PS1, which afaik many prompt styles use

**Comment by mmathys** [comment]
You're right. How about this approach:

```bash
if [ -z "$PS1_old" ]; then
  # PS1_old is not set
  export PS1_old=$PS1
fi
export PS1="(faasm) $PS1_old"
```
