### ISSUE TITLE
faasmctl cli.python ：Waiting for python virtual environment to be ready

### ISSUE THREAD

**Issue by qiyangbo** [faasm/faasm#798]
Hello,
I executed the command "faasmctl cli.python", but the terminal keeps showing me this message, as follows:
(faasm) qiyangbo@qiyangbo-VirtualBox:~/faasm-02$ faasmctl cli.python
[+] Building 0.0s (0/0)                                                                                             docker:default
[+] Running 1/1
 ✔ Container faasm-745098-python-1  Started                                                                                   0.0s 
[+] Copying 1/0
 ✔ faasm-745098-python-1 copy /home/qiyangbo/faasm-02/faasm.ini to faasm-745098-python-1:/tmp/faasm.ini Copied                0.0s 
Waiting for python virtual environment to be ready at /home/qiyangbo/faasm-02/venv-bm/lib/python3.10/site-packages/faasmctl/.config/faasm-source/0.9.1/clients/python/venv/faasm_venv.BUILT ...
Waiting for python virtual environment to be ready at /home/qiyangbo/faasm-02/venv-bm/lib/python3.10/site-packages/faasmctl/.config/faasm-source/0.9.1/clients/python/venv/faasm_venv.BUILT ...
Waiting for python virtual environment to be ready at /home/qiyangbo/faasm-02/venv-bm/lib/python3.10/site-packages/faasmctl/.config/faasm-source/0.9.1/clients/python/venv/faasm_venv.BUILT ...
Waiting for python virtual environment to be ready at /home/qiyangbo/faasm-02/venv-bm/lib/python3.10/site-packages/faasmctl/.config/faasm-source/0.9.1/clients/python/venv/faasm_venv.BUILT ...

**Comment by csegarragonz** [comment]
Hi @qiyangbo thanks for using Faasm!

What steps have you followed to get Faasm running? Have you followed the [quick start](https://github.com/faasm/faasm/tree/main#quick-start) guide?

Aslo, it seems that you are running quite an out-of-date version of Faasm. Would you mind deleting the Faasm directory, and following the quick start instructions from scratch again, with the latest `main` branch?

Please let me know if you still encounter further issues!

**Comment by qiyangbo** [comment]
Thank you for your response. I followed your instructions and used the latest main branch to get Faasm running, but unfortunately, I am still facing the same issue.

(faasm) (base) qiyangbo@qiyangbo-VirtualBox:~/faasm$ faasmctl cli.cpp
[+] Running 14/14
 ✔ cpp 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                                                                     399.7s 
   ✔ b65bcf19d144 Already exists                                                                                                                                                                                                                                              0.0s 
   ✔ efb55d6915a3 Already exists                                                                                                                                                                                                                                              0.0s 
   ✔ 0007c8fa273d Already exists                                                                                                                                                                                                                                              0.0s 
   ✔ 0d63ffa2a3e4 Already exists                                                                                                                                                                                                                                              0.0s 
   ✔ 0fff9de8d594 Already exists                                                                                                                                                                                                                                              0.0s 
   ✔ 0277d40cc262 Pull complete                                                                                                                                                                                                                                             168.6s 
   ✔ 31b8ee38d5f9 Pull complete                                                                                                                                                                                                                                             359.7s 
   ✔ aa28b649e286 Pull complete                                                                                                                                                                                                                                              15.0s 
   ✔ e301a5316d92 Pull complete                                                                                                                                                                                                                                             184.2s 
   ✔ 8e76c2f5c236 Pull complete                                                                                                                                                                                                                                             194.8s 
   ✔ 600b78aaa478 Pull complete                                                                                                                                                                                                                                             208.5s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                                                                                                             196.6s 
   ✔ 626a43715007 Pull complete                                                                                                                                                                                                                                             198.5s 
[+] Building 0.0s (0/0)                                                                                                                                                                                                                                             docker:default
[+] Running 1/1
 ✔ Container faasm-682131-cpp-1  Started                                                                                                                                                                                                                                      0.3s 
[+] Copying 1/0
 ✔ faasm-682131-cpp-1 copy /home/qiyangbo/faasm/faasm.ini to faasm-682131-cpp-1:/tmp/faasm.ini Copied                                                                                                                                                                         0.0s 
Waiting for python virtual environment to be ready at /home/qiyangbo/faasm/venv-bm/lib/python3.10/site-packages/faasmctl/.config/faasm-source/0.12.0/clients/cpp/venv/faasm_venv.BUILT ...
Waiting for python virtual environment to be ready at /home/qiyangbo/faasm/venv-bm/lib/python3.10/site-packages/faasmctl/.config/faasm-source/0.12.0/clients/cpp/venv/faasm_venv.BUILT ...

I wonder if there are any additional steps I can take to resolve this issue or if you have any suggestions on how to proceed.

**Comment by qiyangbo** [comment]
Just to clarify.The Python environment in the virtual environment created using quick start is 3.6.9. Will this have any impact on subsequent steps or processes?

**Comment by csegarragonz** [comment]
mmm yes, that might be it. is there any reason why you can not use `python3.10` ?

In summary, the first time you spawn a container, the container process will run `source ./bin/workon.sh` (inside the container) which will populate `./venv` (note that, outside the container, the virtual environment is populated in `./venv-bm`).

Once `source ./bin/workon.sh` finishes, it creates a file `faasm_venv.BUILT`. We wait for that file to be created to `exec` into the container so that all dependencies are installed (and `inv -l` works).

My guess is that `source ./bin/workon.sh` is failing inside the container. A way to debug this would be to print the container logs:

```bash
# Overall health checks
faasmctl status

# Specific container logs
faasmctl logs -s cpp
```

maybe you can post this logs here?

Also, before running this again, make sure to stop the deployment and also remove the `./venv` directories to ensure a fresh start:

```bash
faasmctl delete
rm -rf ./venv-bm
source ./bin/workon.sh
faasmctl deploy.compose
```

**Comment by csegarragonz** [comment]
Hi, will close the issue but please re-open if you still face problems!
