### ISSUE TITLE
How to directly access the available service by curl?

### ISSUE THREAD

**Issue by czq693497091** [faasm/faasm#803]
For example, after fassmctl cli.cpp a venv enviroment is created, we can invoke the hello function by "inv func.invoke demo hello" and we can access the service. How can we directly curl a url outside the venv to get the hello?

**Comment by csegarragonz** [comment]
hey @czq693497091 thanks for using Faasm!

I would suggest you take a look how `inv func.invoke` is implemented. In particular, you should look at the following python code in the [`faasmctl` repo](https://github.com/faasm/faasmctl/blob/main/faasmctl/util/invoke.py#L52-L104).

Please let me know if this fixes your issue!

**Comment by csegarragonz** [comment]
Closing for now, feel free to re-open if the error still persists!
