### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by jedisct1** [faasm/faasm#805]
GitHub still shows 0.9.2 as the latest release, even though massive changes have been made since.

This is a bit annoying, but GitHub doesn't automatically create releases from tags.

Maybe you should create releases from new tags, just so that GitHub shows the correct information?

**Comment by csegarragonz** [comment]
Yes, that is a good point.

We are pretty diligent with tagging new code versions, so I think the easiest fix would be to automate the release generation process when we make a new tag of `main` branch ([here](https://github.com/faasm/faasm/blob/main/.github/workflows/release.yml)).

I'll keep the issue open and work on it the next time we make a new code tag.

**Comment by csegarragonz** [comment]
FWIW, I have also manually published a new release for code tag `v0.15.0`: https://github.com/faasm/faasm/releases/tag/v0.15.0
