### ISSUE TITLE
Inmemory Global State IP

### ISSUE THREAD

**Issue by PancakeTY** [faasm/faasm#819]
Dear developer,

I am interested in your program, especially its state field. But in the Faasm document, state pull and state push functions interact with the global state server. (what I thought, should be the state server in the upload server) 
However, in your code, the mainIP of getInMemoryStateRegistry is the worker who created this state. Could you please tell me where can I set the global state IP in .env? Or have you changed the state server logic?

I run the worker in my vscode and my .env is like that:
FAASM_LOCAL_DIR=/usr/local/faasm
S3_HOST=xxx.xxx
PLANNER_HOST=xxx.xxx
REDIS_QUEUE_HOST=xxx.xxx
REDIS_STATE_HOST=xxx.xxx

In the state_offset example and its faasmWriteState function. The debug enters the **std::string InMemoryStateRegistry::getMasterIP** function.
In the following code, the main IP of this KV is set to the worker's IP.
 if (mainIPBytes.empty()) {
            mainIPBytes = faabric::util::stringToBytes(thisIP);
            redis.set(mainKey, mainIPBytes);
        }

Thank you very much!
Tianyu

**Comment by PancakeTY** [comment]
And later, in this example's faasmPushState function. It will try to push the state to this worker's state server (who creates this KV).

**Comment by PancakeTY** [comment]
Or I should just set the endpointHost in .env to the upload server's host?

**Comment by csegarragonz** [comment]
Hey @PancakeTY thanks for using Faasm!

As a disclaimer, Faasm's two-tier state system is only maintained for backwards-compatibility but has not been developed for a number of years now. That being said, it should still work!

What is your exact problem?

From your issue description, I think there is a confusion with the concept of "master".
In the two-layer state system, the master of a piece of state is, indeed, the entity (i.e. worker) that has created it.

The `upload` server can be used to upload WASM and files to be used by applications running in Faasm.
WASM and files are stored in the `upload` server (which is backed by `minio`).
The two-layered state-sharing sub-system works either in-memory or backed by `redis-state`.

`redis-queue` is not used anymore, and we need to remove it.

**Comment by PancakeTY** [comment]
> csegarragonz

Hi Carlos!

Thank you for your detailed explanation. It is exactly what I want. 

I will implement my research on top of a Stateful Serverless Platform. After comparing different systems, I found that Faasm is the best one. I had to learn the job of each sub-server first and was confused about some concepts. Your explanation answered my question.

May I ask you another silly question? If multiple invokes of the same function are called at the same time. Can Faasm run the same function in parallel? Can Faasm run multiple instances of the same function in the same worker or different workers at the same time? (I thought it could since the State KV value has read lock and write lock).

Thank you for your help.

**Comment by csegarragonz** [comment]
No worries at all, glad to help!

The concept of `worker` in Faasm (as mentioned in the `docker-compose` or the `k8s` deployment files), corresponds to one-process running in one container running in one VM.

One `worker` may run arbitrarily many Faaslets. Each Faaslet executes one function.
If multiple instances of the same function are invoked at the same time, Faasm will start one Faaslet per function (not necessarily a new worker).
If the same function is invoked repeatedly, Faasm will re-use "warm" Faaslets that have already executed the same function before.

Hope this clarifies your question.
I am gonna go ahead and close the issue, but please feel free to open another one if you have other questions or problems running Faasm!

**Comment by PancakeTY** [comment]
Thank you for your help! Your answer resolved my confusion! Cheers :)
