### ISSUE TITLE
About possible integration of MPI Lammps Migration

### ISSUE THREAD

**Issue by victoryang00** [faasm/faasm#826]
Hi, I found the Lammps workload mentioned in the [Faabric](https://arxiv.org/pdf/2302.11358.pdf) paper are doing application-level checkpoint restore or more broadly CRIU. We are proposing [MVVM](https://github.com/Multi-V-VM/MVVM) and [presentation](https://docs.google.com/presentation/d/110wHr2cuvyYOofnO2pKRI1c3dmEAyV8zvrmX_IAsAmk/edit?usp=sharing) as a WAMR live migration solution for AOT and want to tune Lammps as a workload. However, I'm a bit confused to setup the environment. Does Faasm have a standalone test for debugging the Lammps workload or integrating our work into Faasm?

**Comment by csegarragonz** [comment]
Hi!

Thanks for reaching out, this is very interesting and very relevant/related work to what we are doing in Faabric!
I have skimmed through the presentation and have a few questions to ask to see if we could integrate MVVM with Faasm/Faabric.

To run LAMMPS with Faasm/Faabric, you may follow the instructions in the [examples](https://github.com/faasm/examples) repo. In particular, we build (aka cross-compile) LAMMPS as part of the CI build [here](https://github.com/faasm/examples/blob/main/.github/workflows/tests.yml#L87-L88), and execute a simple simulation [here](https://github.com/faasm/examples/blob/main/.github/workflows/tests.yml#L260-L262).

Please let me know if you do not manage to get it to run.

Also, would you consider having a call to discuss integrations of MVVM with Faasm/Faabric? You may find my academic email on my [website](https://carlossegarra.com).

**Comment by victoryang00** [comment]
Thanks a lot!
