### ISSUE TITLE
run microbench_runner failed

### ISSUE THREAD

**Issue by lyuxiaosu** [faasm/faasm#842]
Hi, I want to run [**microbench_runner**](https://github.com/faasm/experiment-microbench). I could build out **microbench_runner** but failed with building Polybench/C due to missing numpy package (I installed numpy inside the container, but it still cannot find it and I don't know how to figure it out, might related to virtual environment setting, I am not a python expert). So I want to setup a local cluster with `faasmctl deploy.compose` and build/upload **CPP** functions, let` microbench_runner` to access to this local cluster. However, the local cluster has a different NetworkMode from this **fassm-cli** container, leading to  **microbench_runner** inside  **fassm-cli** cannot access to the local cluster. I don't know how to set the same NetworkMode for the cluster and the **fassm-cli**, is there any suggestions for this? I want **microbench_runner** access to the local cluster that `faasmctl deploy.compose` deployment. Thank you for your help.

**Comment by csegarragonz** [comment]
Hi @lyuxiaosu!

Alas, the repo you linked is quite out-of-date and should be archived.

If you want to run the Polybench/C benchmark with a compose cluster (without microbench), you can see how we do it here: https://github.com/faasm/experiment-mpi/tree/main/tasks/polybench

To run each Polybench/C function manually, one by one, using `faasmctl` you can take a look here: https://github.com/faasm/examples/blob/main/.github/workflows/tests.yml#L227-L256

Lastly, you should be able to use the microbench runner, please see the runner included in Faasm's source tree: https://github.com/faasm/faasm/blob/main/src/runner/MicrobenchRunner.cpp

Hope this helps!

**Comment by lyuxiaosu** [comment]
Thanks for your reply. I used the latest faasmctl and faasm, it seems the latest version can get the wall time and execution time, like this:

```
======================= Faasm Execution =========================
Function:                       demo/hello
Return value:                   0
Wall time:                      2.01 s
Execution time:                 0.00 s
-----------------------------------------------------------------
Output:
Hello Faasm!
=================================================================
```
Is the execution time calucated by the planner and taken by the response msg to the client?

**Comment by lyuxiaosu** [comment]
OK, I saw your code update, this execution time is helpful for my testing because we need to measure some cost on the server side.

I finally can make **microbench_runner**  to execute demo hello applicaton, but the nng sending back msg timeout due to TCP timeout, I guess the packaget cannot go back due to the container private IP things. You can close this issue now. Thanks
