### ISSUE TITLE
Waiting for python virtual environment to be ready

### ISSUE THREAD

**Issue by chooper666** [faasm/faasm#845]
when I execute this comment "faasmctl cli.python",then ...

this problem bother me for a long time

<img width="1392" alt="image" src="https://github.com/faasm/faasm/assets/67227470/765e5cf5-9675-432e-b5b2-3521fd2e2eea">

**Comment by csegarragonz** [comment]
Hi @chooper666 , thanks for using Faasm!

What steps have you followed to set-up the environment?
Could you follow the quick-start guide on a new directory and see if the error persists?

```bash
# clone repo
cd faasm
git submodule update --init

source ./bin/workon.sh
faasmctl deploy.compose

faasmctl cli.python
```

note that the quick start steps above are tested regularly as part of the CI/CD, so they should work.

**Comment by chooper666** [comment]
> Hi @chooper666 , thanks for using Faasm!
> 
> What steps have you followed to set-up the environment? Could you follow the quick-start guide on a new directory and see if the error persists?
> 
> ```shell
> # clone repo
> cd faasm
> git submodule update --init
> 
> source ./bin/workon.sh
> faasmctl deploy.compose
> 
> faasmctl cli.python
> ```
> 
> note that the quick start steps above are tested regularly as part of the CI/CD, so they should work.

umm, I actually follow this guide, and all step are completed.Then comes to the result that show from the picture.

**Comment by chooper666** [comment]
> Sorry, I should have been more precise, given that you are not mounting the source code, could you run the following steps:
> 
> ```shell
> source ./bin/workon.sh
> faasmctl deploy.compose --clean
> 
> faasmctl cli.python
> ```
> 
> (note the `--clean` flag)
> 
> you may also run (from another container):
> 
> ```shell
> faasmctl logs -s python -f
> ```

I try again.then it shows as here.
<img width="876" alt="image" src="https://github.com/faasm/faasm/assets/67227470/b7ff00ea-73cb-48a6-946d-f673ca49aeb8">

**Comment by chooper666** [comment]
> Sorry, I should have been more precise, given that you are not mounting the source code, could you run the following steps:
> 
> ```shell
> source ./bin/workon.sh
> faasmctl deploy.compose --clean
> 
> faasmctl cli.python
> ```
> 
> (note the `--clean` flag)
> 
> you may also run (from another container):
> 
> ```shell
> faasmctl logs -s python -f
> ```

oh, it finally comes true! thx and keep contact if I meet some other questions.really thanks for your patient.
<img width="876" alt="image" src="https://github.com/faasm/faasm/assets/67227470/1fa6d3f3-23a6-49bb-8193-608aa0dff6c9">

**Comment by chooper666** [comment]
<img width="1092" alt="image" src="https://github.com/faasm/faasm/assets/67227470/78007875-e8e7-4e36-9a96-4194c4ae5c0d">
when I try to do the benchmark test as this link https://github.com/faasm/experiment-microbench
then type this command, the result show as the first pic.
<img width="888" alt="image" src="https://github.com/faasm/faasm/assets/67227470/71c4d922-12ba-4a83-9bf7-c9f17bd6d6f9">
