### ISSUE TITLE
Question: How to create new workers dynamically.

### ISSUE THREAD

**Issue by PancakeTY** [faasm/faasm#855]
Dear Carlos,

Thank for your upgrading to LLVM17!

Now, I deploy a docker faasm cluster with 2 workers at first and then create the faasm.cli container by using faasmctl. I attach faasm.cli container to vscode editor as programming environment. Will it lead some accidental problem except the tests? Your Catch2 tests create the new worker in the faasm.cli container. It might lead some problems. 

Or, could you please tell me how you set up the programming environment?

I want to run some tests with different number of real worker containers.  So, I want to add new workers or remove workers container dynamically. I have read the faasmctl code, but can not find the related functions.
If I want to add new workers, Is it OK to create new worker container by using docker and save to worker container information to faasm.ini?

Thank you for your help.
Tianyu

**Comment by csegarragonz** [comment]
Hi Tianyu, 

Are you running into any problems using VScode attached to the `faasm-cli` container?
I do not use this set up personally, but I know of people who have used it in the past, and I don't see why there should be any problems.

Regarding the scaling up feature, you are right that it is not directly available from `faasmctl`.
In theory, you _should_ be able to run something along the lines of `docker compose scale --workers=<N> --no-recreate` but it would not work as `faasmctl` sets a lot of env. vars (like the compose project name).

That being said, it should be relatively easy to add a `faasmctl scale worker <N>`.
I am a bit busy at the moment, but you could also try adding the feature to `faasmctl` yourself, I should be able to provide some pointers/feedback.

Hope this helps, and feel free to open a specific issue in `faasmctl` and maybe close this one.

**Comment by PancakeTY** [comment]
Hi Carlos,

Thank you for your reply. 

Currently, there is no problem by using VScode attached to the faasm-cli container. It's good to know others also have ever used it. I will open an issue when facing problem. 

Thank you for your reply about the scaling issue. I am happy to add scale function myself in the future (I am also very busy now). I will close this issue.

Thank you,
Tianyu

**Comment by csegarragonz** [comment]
@PancakeTY FYI faasm/faasmctl#77

**Comment by PancakeTY** [comment]
> @PancakeTY FYI [faasm/faasmctl#77](https://github.com/faasm/faasmctl/pull/77)

Thank you for your help! It is very useful to me. Thank you.
