### ISSUE TITLE
Benchmarks for the ML inference + learning mentioned in paper?

### ISSUE THREAD

**Issue by alexthomasv** [faasm/faasm#865]
Hello! I wanted to do a comparison benchmark with Faasm, could I be pointed to where the benchmarks for the HOGWILD training and Tensorflow-lite inference serving benchmarks are located? I couldn't find it under examples. Thank you!

**Comment by csegarragonz** [comment]
hey! unfortunately i don't think we have the exact scripts for the training and inference benchmarks anymore...

the silver linning is that you should still be able to cross-compile tensorflow lite using the script in the [examples repo](https://github.com/faasm/examples/blob/main/tasks/tensorflow.py), and then run whatever serving workload you wish.

fwiw, we cross-compile tf lite as a library, and statically link it to a C program, you can see [this example here](https://github.com/faasm/examples/tree/main/func/tf).

please let me know if i can help any further!
