### ISSUE TITLE
22/05/2024 paper?

### ISSUE THREAD

**Issue by jedisct1** [faasm/faasm#872]
Hi!

I saw a reference to a paper submitted on 22/05/2024 in the last release.

Is that paper publicly accessible? Do you have to it?

Thanks and keep up the good work!

-Frank.

**Comment by csegarragonz** [comment]
Hey @jedisct1!

Thank you very much for keeping an eye on the repo activity :)

The paper is submitted and under review, but if you contact me at the email in my profile I can share a pre-print.

Carlos

**Comment by jedisct1** [comment]
Has the paper been published?
