### ISSUE TITLE
Microbenchmark runner

### ISSUE THREAD

**Issue by HiranmayeeKadali** [faasm/faasm#873]
Hi! Is there someway else to measure performance metrics related to what I'm running in the container, I have trouble with microbenchmark runner as well as vector and performance copilot.

**Comment by csegarragonz** [comment]
hi i would take a look at this issue: https://github.com/faasm/faasm/issues/842

let me know if that helps!

**Comment by HiranmayeeKadali** [comment]
Hii Carlos, 
Thankyou so much I hope it works. I'll look into it. I have a need to monitor performance metrics as well on the host to see how it works. I have worked with pcp and grafana (since vector is outof date) / prometheus and grafana as well but I'm failing to connect to grafana from prometheus side and receiving bad request error(though it runs without any issue on the host). Is there some way you can help me with it. Your advice will be very helpful for my thesis work.

**Comment by csegarragonz** [comment]
Hi, I'm sorry but we do not use any of those performance monitoring tools!

Do let me know if you manage to hook it into Faasm.

**Comment by HiranmayeeKadali** [comment]
Hey @csegarragonz, 
I have deployed Faasm on a K8 cluster with 4 nodes and am using faasmctl cli.cpp to invoke and run functions on. I invoked faasmc cli using docker compose and am running microbenchmark experimentation there after creating an executable. I get the following issue. Please let me know if I'm missing anything or how should I work with faasm-cli when faasm is running on k8 cluster.
![WhatsApp Image 2024-06-04 at 14 11 35](https://github.com/faasm/faasm/assets/167014484/1ef11b76-5165-4266-917e-a92e1cc45901)

**Comment by csegarragonz** [comment]
I am not sure what are you trying to do here. Could you be more specific?

What steps have you followed?
What do you want to run and where?

**Comment by HiranmayeeKadali** [comment]
Hii , 
I'm trying to run the microbench_runner experiment to see the results. But since I deployed faasm on k8 cluster I get (Can't call cli.faasm on a k8 cluster run time error) So I have tried to run the microbench_runner on faasm-cli by invoking it as a container using (docker compose). I'm new to this, can you let me know if I'm missing something please.
![WhatsApp Image 2024-06-05 at 10 49 23](https://github.com/faasm/faasm/assets/167014484/e29072f2-a66f-4437-bcdd-64908f808594)

**Comment by csegarragonz** [comment]
You should not use the microbench runner, use what is described here: https://github.com/faasm/faasm/issues/842
